### ISSUE TITLE
No module named 'memory_profiler'

### ISSUE THREAD

**Issue by likecu** [PanJinquan/Human-Keypoints-Detection#1]
Traceback (most recent call last):
  File "E:/python_projects/pythonProject1/demo.py", line 20, in <module>
    from libs.detector.libs.detector.detector import Detector
  File "E:\python_projects\pythonProject1\libs\detector\libs\detector\detector.py", line 17, in <module>
    from utils import image_processing, file_processing, debug
  File "E:\python_projects\pythonProject1\utils\debug.py", line 13, in <module>
    from memory_profiler import profile
ModuleNotFoundError: No module named 'memory_profiler'

**Comment by PanJinquan** [comment]
pip install memory_profiler
